# Generated by Django 2.2.9 on 2022-12-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группы по интересам', 'verbose_name_plural': 'Группы по интересам'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Посты', 'verbose_name_plural': 'Посты'},
        ),
    ]
