# Generated by Django 2.2.6 on 2022-12-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20221218_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Посты', 'verbose_name_plural': 'Посты'},
        ),
    ]
